### PR TITLE
Added imports for the Fail monad

### LINKED ISSUE #8: Failing to build Watson: MonadFail not in scope
Tried to install holmes from Cabal and got this error:
```
src/Control/Monad/Watson.hs:55:10: error:
    Not in scope: type constructor or class ‘MonadFail’
   |
55 | instance MonadFail (Watson h) where
   |          ^^^^^^^^^
```

I'm using GHC version 8.6.5, it seems to be failing on Hackage CI as well.

### PR DESCRIPTION
**Pull request by Soupstraw**
This should fix #8. I tested it with GHC 8.6.5 and succeeded

### CODE REVIEW

**Comment by Soupstraw** [comment]
Just realized there is already a pull request for this.

**Comment by i-am-tom** [comment]
Hello! Yes, sorry it hasn't yet been merged - I've been unexpectedly busy with quarantines and family obligations. I'll try to get this sorted tonight!

**Comment by Soupstraw** [comment]
I added the pragmas as suggested in the other PR, should be good now.

**Comment by i-am-tom** [comment]
Aah, fantastic! Thanks very much :) I'll do a release. Thanks for your patience & sorry it took so long to get done...

**Pull request merged**
